jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: GetText
      run: sudo apt install gettext
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Generate override.properties
      run: 'rm -f override.properties

        echo "build.built-by=GitHub Actions" >> override.properties

        echo "noExe=true" >> override.properties

        '
    - continue-on-error: true
      name: build with Ant
      run: ant distclean pkg
    - continue-on-error: true
      name: Upload installer.jar
      uses: actions/upload-artifact@v4
      with:
        name: I2P-install-${{ github.sha }}.jar
        path: install.jar
  build-java7:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: GetText
      run: sudo apt install gettext
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Generate override.properties
      run: 'git clone https://github.com/eyedeekay/openjdk-7 "$HOME/openjdk-7"

        rm -f override.properties

        echo "build.built-by=GitHub Actions" >> override.properties

        echo "noExe=true" >> override.properties

        echo "javac.compilerargs=-bootclasspath $HOME/openjdk-7/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar:$HOME/openjdk-7/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar
        -Xlint:all" >> override.properties

        '
    - continue-on-error: true
      name: build with Ant
      run: ./installer/resources/maven-dev-release.sh 1
    - continue-on-error: true
      name: Upload servlet-i2p.jar
      uses: actions/upload-artifact@v4
      with:
        name: servlet-i2p-${{ github.sha }}.jar
        path: pkg-mavencentral/servlet-i2p*.jar
    - continue-on-error: true
      name: Upload streaming.jar
      uses: actions/upload-artifact@v4
      with:
        name: streaming-${{ github.sha }}.jar
        path: pkg-mavencentral/streaming*.jar
    - continue-on-error: true
      name: Upload mstreaming.jar
      uses: actions/upload-artifact@v4
      with:
        name: mstreaming-${{ github.sha }}.jar
        path: pkg-mavencentral/mstreaming*.jar
    - continue-on-error: true
      name: Upload router.jar
      uses: actions/upload-artifact@v4
      with:
        name: router-${{ github.sha }}.jar
        path: pkg-mavencentral/router*.jar
    - continue-on-error: true
      name: Upload i2p.jar
      uses: actions/upload-artifact@v4
      with:
        name: i2p-${{ github.sha }}.jar
        path: pkg-mavencentral/i2p*.jar
  javadoc-latest:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Setup Pages
      uses: actions/configure-pages@v4
    - continue-on-error: true
      name: GetText
      run: sudo apt install gettext
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Generate override.properties
      run: 'rm -f override.properties

        echo "build.built-by=GitHub Actions" >> override.properties

        echo "noExe=true" >> override.properties

        '
    - continue-on-error: true
      name: build with Ant
      run: ant distclean javadoc updater
    - continue-on-error: true
      name: zip javadoc
      run: cp i2pupdate.zip build/javadoc/i2pupdate.zip && zip -r javadoc.zip build/javadoc
    - continue-on-error: true
      name: Upload javadoc.zip
      uses: actions/upload-artifact@v4
      with:
        name: I2P-javadoc-${{ github.sha }}.zip
        path: javadoc.zip
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/javadoc
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
permissions:
  contents: read
  id-token: write
  pages: write
