jobs:
  repo-sync:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        destination_branch: master
        github_token: ${{ secrets.PAT }}
        source_branch: master
        source_repo: https://i2pgit.org/i2p-hackers/i2p.i2p
on:
  repository_dispatch:
    types: trigger-ga___github-sync.yml
